// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jomeyunpmftiayhtlitn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbWV5dW5wbWZ0aWF5aHRsaXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODU2MzYsImV4cCI6MjA1OTM2MTYzNn0.eV4YKNwMxX8jNPFoDQnTS1Obh_XgmeQtbkhEs5k9PQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);